# Generated by Django 4.1a1 on 2022-06-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.CharField(default="-", max_length=255),
            preserve_default=False,
        ),
    ]
