# Generated by Django 4.1a1 on 2022-06-11 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_address_zip"),
    ]

    operations = [migrations.RunSQL()]
